version: '3.9'

volumes:
  rabbitmq_data:

networks:
  customer_net:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin123"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - customer_net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: unless-stopped

  api:

    image: customer-mangment:latest  
    container_name: customer_api
    environment:
      ConnectionStrings__DefaultConnection: "Server=host.docker.internal,1433;Database=CustomerManagement;User Id=sa;Password=StrongPass@123;MultipleActiveResultSets=True;TrustServerCertificate=True;Encrypt=False"
      MongoDB__ConnectionString: "mongodb://host.docker.internal:27017"
      MongoDB__DatabaseName: "CustomerManagement"
      FeatureFlags__UseMongoDb: "true"
      RabbitMQ__Host: "rabbitmq"
      RabbitMQ__Port: "5672"
      RabbitMQ__Username: "admin"
      RabbitMQ__Password: "admin123"    
      

    ports:
      - "5046:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - customer_net
    restart: "no"