version: '3.9'

volumes:
  mongo_data:
  rabbitmq_data:

networks:
  customer_net:
    driver: bridge

services:

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "admin123"
      MONGO_INITDB_DATABASE: CustomerManagement
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - customer_net
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 20s
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin123"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - customer_net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: unless-stopped

  api:

    image: customer-mangment:latest  
    container_name: customer_api
    environment:
      ConnectionStrings__DefaultConnection: "Server=host.docker.internal,1433;Database=CustomerManagement;User Id=sa;Password=StrongPass@123;MultipleActiveResultSets=True;TrustServerCertificate=True;Encrypt=False"
      MongoDB__ConnectionString: "mongodb://admin:admin123@mongodb:27017"
      MongoDB__DatabaseName: "CustomerManagement"
      FeatureFlags__UseMongoDb: "false"
      RabbitMQ__Host: "rabbitmq"
      RabbitMQ__Port: "5672"
      RabbitMQ__Username: "admin"
      RabbitMQ__Password: "admin123"    
      

    ports:
      - "5046:8080"
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - customer_net
    restart: "no"