//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
namespace Customer_Mangment_Integrate.Test.Common
{
    using Customer_Mangment.CQRS.Identity.Dto;
    using System = global::System;
    //FROM REF
    /// <summary>
    /// Single unified client: Auth + CustomerReport + CustomerAddress + Customer + RabbitMQ
    /// </summary>
    public partial class Client
    {
        private string _baseUrl;

        private System.Net.Http.HttpClient _httpClient;
        private static System.Lazy<Newtonsoft.Json.JsonSerializerSettings> _settings = new System.Lazy<Newtonsoft.Json.JsonSerializerSettings>(CreateSerializerSettings, true);
        private Newtonsoft.Json.JsonSerializerSettings _instanceSettings;

        public Client(System.Net.Http.HttpClient httpClient)
        {
            BaseUrl = "http://localhost:5000/";
            _httpClient = httpClient;
            Initialize();
        }

        private static Newtonsoft.Json.JsonSerializerSettings CreateSerializerSettings()
        {
            var settings = new Newtonsoft.Json.JsonSerializerSettings();
            UpdateJsonSerializerSettings(settings);
            return settings;
        }

        public string BaseUrl
        {
            get { return _baseUrl; }
            set
            {
                _baseUrl = value;
                if (!string.IsNullOrEmpty(_baseUrl) && !_baseUrl.EndsWith("/"))
                    _baseUrl += '/';
            }
        }

        protected Newtonsoft.Json.JsonSerializerSettings JsonSerializerSettings { get { return _instanceSettings ?? _settings.Value; } }

        static partial void UpdateJsonSerializerSettings(Newtonsoft.Json.JsonSerializerSettings settings);
        partial void Initialize();
        partial void PrepareRequest(System.Net.Http.HttpClient client, System.Net.Http.HttpRequestMessage request, string url);
        partial void PrepareRequest(System.Net.Http.HttpClient client, System.Net.Http.HttpRequestMessage request, System.Text.StringBuilder urlBuilder);
        partial void ProcessResponse(System.Net.Http.HttpClient client, System.Net.Http.HttpResponseMessage response);

        // ── Auth ─────────────────────────────────────────────────────────

        /// <summary>Generates an access and refresh token for a valid user.</summary>
        public virtual System.Threading.Tasks.Task<TokenServerResponse> GenerateTokenAsync(GenerateTokenQuery body)
            => GenerateTokenAsync(body, System.Threading.CancellationToken.None);

        public virtual async System.Threading.Tasks.Task<TokenServerResponse> GenerateTokenAsync(GenerateTokenQuery body, System.Threading.CancellationToken cancellationToken)
        {
            if (body == null) throw new System.ArgumentNullException("body");
            var client_ = _httpClient;
            using (var request_ = new System.Net.Http.HttpRequestMessage())
            {
                var json_ = Newtonsoft.Json.JsonConvert.SerializeObject(body, JsonSerializerSettings);
                var content_ = new System.Net.Http.StringContent(json_);
                content_.Headers.ContentType = System.Net.Http.Headers.MediaTypeHeaderValue.Parse("application/json");
                request_.Content = content_;
                request_.Method = new System.Net.Http.HttpMethod("POST");
                request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                var urlBuilder_ = new System.Text.StringBuilder();
                if (!string.IsNullOrEmpty(_baseUrl)) urlBuilder_.Append(_baseUrl);
                urlBuilder_.Append("api/Auth/token/generate");
                PrepareRequest(client_, request_, urlBuilder_);
                var url_ = urlBuilder_.ToString();
                request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);
                PrepareRequest(client_, request_, url_);

                var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                try
                {
                    var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                    foreach (var item_ in response_.Headers) headers_[item_.Key] = item_.Value;
                    if (response_.Content?.Headers != null)
                        foreach (var item_ in response_.Content.Headers) headers_[item_.Key] = item_.Value;
                    ProcessResponse(client_, response_);
                    var status_ = (int)response_.StatusCode;
                    if (status_ == 200)
                    {
                        var obj_ = await ReadObjectResponseAsync<TokenServerResponse>(response_, headers_, cancellationToken).ConfigureAwait(false);
                        if (obj_.Object == null) throw new ApiException("Response was null which was not expected.", status_, obj_.Text, headers_, null);
                        return obj_.Object;
                    }
                    else if (status_ == 400) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Bad Request", status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 404) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Not Found", status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 409) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Conflict", status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 500) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Internal Server Error", status_, obj_.Text, headers_, obj_.Object, null); }
                    else { var data_ = response_.Content == null ? null : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false); throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, data_, headers_, null); }
                }
                finally { response_.Dispose(); }
            }
        }

        /// <summary>Refreshes access token using a valid refresh token.</summary>
        public virtual System.Threading.Tasks.Task<TokenServerResponse> RefreshTokenAsync(RefreshTokenQuery body)
            => RefreshTokenAsync(body, System.Threading.CancellationToken.None);

        public virtual async System.Threading.Tasks.Task<TokenServerResponse> RefreshTokenAsync(RefreshTokenQuery body, System.Threading.CancellationToken cancellationToken)
        {
            if (body == null) throw new System.ArgumentNullException("body");
            var client_ = _httpClient;
            using (var request_ = new System.Net.Http.HttpRequestMessage())
            {
                var json_ = Newtonsoft.Json.JsonConvert.SerializeObject(body, JsonSerializerSettings);
                var content_ = new System.Net.Http.StringContent(json_);
                content_.Headers.ContentType = System.Net.Http.Headers.MediaTypeHeaderValue.Parse("application/json");
                request_.Content = content_;
                request_.Method = new System.Net.Http.HttpMethod("POST");
                request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                var urlBuilder_ = new System.Text.StringBuilder();
                if (!string.IsNullOrEmpty(_baseUrl)) urlBuilder_.Append(_baseUrl);
                urlBuilder_.Append("api/Auth/token/refresh-token");
                PrepareRequest(client_, request_, urlBuilder_);
                var url_ = urlBuilder_.ToString();
                request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);
                PrepareRequest(client_, request_, url_);

                var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                try
                {
                    var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                    foreach (var item_ in response_.Headers) headers_[item_.Key] = item_.Value;
                    if (response_.Content?.Headers != null)
                        foreach (var item_ in response_.Content.Headers) headers_[item_.Key] = item_.Value;
                    ProcessResponse(client_, response_);
                    var status_ = (int)response_.StatusCode;
                    if (status_ == 200)
                    {
                        var obj_ = await ReadObjectResponseAsync<TokenServerResponse>(response_, headers_, cancellationToken).ConfigureAwait(false);
                        if (obj_.Object == null) throw new ApiException("Response was null which was not expected.", status_, obj_.Text, headers_, null);
                        return obj_.Object;
                    }
                    else if (status_ == 400) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Bad Request", status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 404) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Not Found", status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 409) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Conflict", status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 500) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Internal Server Error", status_, obj_.Text, headers_, obj_.Object, null); }
                    else { var data_ = response_.Content == null ? null : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false); throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, data_, headers_, null); }
                }
                finally { response_.Dispose(); }
            }
        }

        // ── CustomerReport ────────────────────────────────────────────────

        /// <summary>Generates and downloads a PDF report of all customers. Requires the Admin role.</summary>
        public virtual System.Threading.Tasks.Task<FileContentResult> DownloadCustomerReportAsync(System.DateTimeOffset? from, System.DateTimeOffset? to)
            => DownloadCustomerReportAsync(from, to, System.Threading.CancellationToken.None);

        public virtual async System.Threading.Tasks.Task<FileContentResult> DownloadCustomerReportAsync(System.DateTimeOffset? from, System.DateTimeOffset? to, System.Threading.CancellationToken cancellationToken)
        {
            var client_ = _httpClient;
            using (var request_ = new System.Net.Http.HttpRequestMessage())
            {
                request_.Method = new System.Net.Http.HttpMethod("GET");
                request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/pdf"));

                var urlBuilder_ = new System.Text.StringBuilder();
                if (!string.IsNullOrEmpty(_baseUrl)) urlBuilder_.Append(_baseUrl);
                urlBuilder_.Append("api/CustomerReport/download");
                urlBuilder_.Append('?');
                if (from != null) urlBuilder_.Append(System.Uri.EscapeDataString("from")).Append('=').Append(System.Uri.EscapeDataString(from.Value.ToString("s", System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                if (to != null)   urlBuilder_.Append(System.Uri.EscapeDataString("to")).Append('=').Append(System.Uri.EscapeDataString(to.Value.ToString("s", System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                urlBuilder_.Length--;
                PrepareRequest(client_, request_, urlBuilder_);
                var url_ = urlBuilder_.ToString();
                request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);
                PrepareRequest(client_, request_, url_);

                var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                try
                {
                    var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                    foreach (var item_ in response_.Headers) headers_[item_.Key] = item_.Value;
                    if (response_.Content?.Headers != null)
                        foreach (var item_ in response_.Content.Headers) headers_[item_.Key] = item_.Value;
                    ProcessResponse(client_, response_);
                    var status_ = (int)response_.StatusCode;
                    if (status_ == 200)
                    {
                        var obj_ = await ReadObjectResponseAsync<FileContentResult>(response_, headers_, cancellationToken).ConfigureAwait(false);
                        if (obj_.Object == null) throw new ApiException("Response was null which was not expected.", status_, obj_.Text, headers_, null);
                        return obj_.Object;
                    }
                    else if (status_ == 400) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Bad Request", status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 401) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Unauthorized", status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 404) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Not Found", status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 500) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Internal Server Error", status_, obj_.Text, headers_, obj_.Object, null); }
                    else { var data_ = response_.Content == null ? null : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false); throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, data_, headers_, null); }
                }
                finally { response_.Dispose(); }
            }
        }

        // ── CustomerAddress ───────────────────────────────────────────────

        /// <summary>GetCustomerAddresses</summary>
        public virtual System.Threading.Tasks.Task<System.Collections.Generic.ICollection<AddressDto>> GetAsync(System.Guid? customerId, System.Guid? addressId)
            => GetAsync(customerId, addressId, System.Threading.CancellationToken.None);

        public virtual async System.Threading.Tasks.Task<System.Collections.Generic.ICollection<AddressDto>> GetAsync(System.Guid? customerId, System.Guid? addressId, System.Threading.CancellationToken cancellationToken)
        {
            var client_ = _httpClient;
            using (var request_ = new System.Net.Http.HttpRequestMessage())
            {
                request_.Method = new System.Net.Http.HttpMethod("GET");
                request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                var urlBuilder_ = new System.Text.StringBuilder();
                if (!string.IsNullOrEmpty(_baseUrl)) urlBuilder_.Append(_baseUrl);
                urlBuilder_.Append("api/CustomerAddress/get");
                urlBuilder_.Append('?');
                if (customerId != null) urlBuilder_.Append(System.Uri.EscapeDataString("CustomerId")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(customerId, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                if (addressId  != null) urlBuilder_.Append(System.Uri.EscapeDataString("AddressId")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(addressId,  System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                urlBuilder_.Length--;
                PrepareRequest(client_, request_, urlBuilder_);
                var url_ = urlBuilder_.ToString();
                request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);
                PrepareRequest(client_, request_, url_);

                var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                try
                {
                    var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                    foreach (var item_ in response_.Headers) headers_[item_.Key] = item_.Value;
                    if (response_.Content?.Headers != null)
                        foreach (var item_ in response_.Content.Headers) headers_[item_.Key] = item_.Value;
                    ProcessResponse(client_, response_);
                    var status_ = (int)response_.StatusCode;
                    if (status_ == 200)
                    {
                        var obj_ = await ReadObjectResponseAsync<System.Collections.Generic.ICollection<AddressDto>>(response_, headers_, cancellationToken).ConfigureAwait(false);
                        if (obj_.Object == null) throw new ApiException("Response was null which was not expected.", status_, obj_.Text, headers_, null);
                        return obj_.Object;
                    }
                    else if (status_ == 400) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Bad Request",            status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 401) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Unauthorized",          status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 404) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Not Found",             status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 409) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Conflict",              status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 500) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Internal Server Error", status_, obj_.Text, headers_, obj_.Object, null); }
                    else { var data_ = response_.Content == null ? null : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false); throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, data_, headers_, null); }
                }
                finally { response_.Dispose(); }
            }
        }

        /// <summary>AddAddress</summary>
        public virtual System.Threading.Tasks.Task<AddressDto> AddAsync(System.Guid? customerId, AddAddressReq body)
            => AddAsync(customerId, body, System.Threading.CancellationToken.None);

        public virtual async System.Threading.Tasks.Task<AddressDto> AddAsync(System.Guid? customerId, AddAddressReq body, System.Threading.CancellationToken cancellationToken)
        {
            if (body == null) throw new System.ArgumentNullException("body");
            var client_ = _httpClient;
            using (var request_ = new System.Net.Http.HttpRequestMessage())
            {
                var json_ = Newtonsoft.Json.JsonConvert.SerializeObject(body, JsonSerializerSettings);
                var content_ = new System.Net.Http.StringContent(json_);
                content_.Headers.ContentType = System.Net.Http.Headers.MediaTypeHeaderValue.Parse("application/json");
                request_.Content = content_;
                request_.Method = new System.Net.Http.HttpMethod("POST");
                request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                var urlBuilder_ = new System.Text.StringBuilder();
                if (!string.IsNullOrEmpty(_baseUrl)) urlBuilder_.Append(_baseUrl);
                urlBuilder_.Append("api/CustomerAddress/add");
                urlBuilder_.Append('?');
                if (customerId != null) urlBuilder_.Append(System.Uri.EscapeDataString("CustomerId")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(customerId, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                urlBuilder_.Length--;
                PrepareRequest(client_, request_, urlBuilder_);
                var url_ = urlBuilder_.ToString();
                request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);
                PrepareRequest(client_, request_, url_);

                var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                try
                {
                    var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                    foreach (var item_ in response_.Headers) headers_[item_.Key] = item_.Value;
                    if (response_.Content?.Headers != null)
                        foreach (var item_ in response_.Content.Headers) headers_[item_.Key] = item_.Value;
                    ProcessResponse(client_, response_);
                    var status_ = (int)response_.StatusCode;
                    if (status_ == 200)
                    {
                        var obj_ = await ReadObjectResponseAsync<AddressDto>(response_, headers_, cancellationToken).ConfigureAwait(false);
                        if (obj_.Object == null) throw new ApiException("Response was null which was not expected.", status_, obj_.Text, headers_, null);
                        return obj_.Object;
                    }
                    else if (status_ == 400) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Bad Request",            status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 401) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Unauthorized",          status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 404) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Not Found",             status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 409) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Conflict",              status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 500) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Internal Server Error", status_, obj_.Text, headers_, obj_.Object, null); }
                    else { var data_ = response_.Content == null ? null : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false); throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, data_, headers_, null); }
                }
                finally { response_.Dispose(); }
            }
        }

        /// <summary>GetAddressHistory</summary>
        public virtual System.Threading.Tasks.Task<System.Collections.Generic.ICollection<AddressHistoryDto>> HistoryAsync(System.Guid? customerId)
            => HistoryAsync(customerId, System.Threading.CancellationToken.None);

        public virtual async System.Threading.Tasks.Task<System.Collections.Generic.ICollection<AddressHistoryDto>> HistoryAsync(System.Guid? customerId, System.Threading.CancellationToken cancellationToken)
        {
            var client_ = _httpClient;
            using (var request_ = new System.Net.Http.HttpRequestMessage())
            {
                request_.Method = new System.Net.Http.HttpMethod("GET");
                request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                var urlBuilder_ = new System.Text.StringBuilder();
                if (!string.IsNullOrEmpty(_baseUrl)) urlBuilder_.Append(_baseUrl);
                urlBuilder_.Append("api/CustomerAddress/history");
                urlBuilder_.Append('?');
                if (customerId != null) urlBuilder_.Append(System.Uri.EscapeDataString("CustomerId")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(customerId, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                urlBuilder_.Length--;
                PrepareRequest(client_, request_, urlBuilder_);
                var url_ = urlBuilder_.ToString();
                request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);
                PrepareRequest(client_, request_, url_);

                var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                try
                {
                    var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                    foreach (var item_ in response_.Headers) headers_[item_.Key] = item_.Value;
                    if (response_.Content?.Headers != null)
                        foreach (var item_ in response_.Content.Headers) headers_[item_.Key] = item_.Value;
                    ProcessResponse(client_, response_);
                    var status_ = (int)response_.StatusCode;
                    if (status_ == 200)
                    {
                        var obj_ = await ReadObjectResponseAsync<System.Collections.Generic.ICollection<AddressHistoryDto>>(response_, headers_, cancellationToken).ConfigureAwait(false);
                        if (obj_.Object == null) throw new ApiException("Response was null which was not expected.", status_, obj_.Text, headers_, null);
                        return obj_.Object;
                    }
                    else if (status_ == 400) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Bad Request",            status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 401) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Unauthorized",          status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 404) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Not Found",             status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 409) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Conflict",              status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 500) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Internal Server Error", status_, obj_.Text, headers_, obj_.Object, null); }
                    else { var data_ = response_.Content == null ? null : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false); throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, data_, headers_, null); }
                }
                finally { response_.Dispose(); }
            }
        }

        /// <summary>UpdateAddress</summary>
        public virtual System.Threading.Tasks.Task<Updated> UpdateAsync(System.Guid? addressId, UpdateAddressReq body)
            => UpdateAsync(addressId, body, System.Threading.CancellationToken.None);

        public virtual async System.Threading.Tasks.Task<Updated> UpdateAsync(System.Guid? addressId, UpdateAddressReq body, System.Threading.CancellationToken cancellationToken)
        {
            if (body == null) throw new System.ArgumentNullException("body");
            var client_ = _httpClient;
            using (var request_ = new System.Net.Http.HttpRequestMessage())
            {
                var json_ = Newtonsoft.Json.JsonConvert.SerializeObject(body, JsonSerializerSettings);
                var content_ = new System.Net.Http.StringContent(json_);
                content_.Headers.ContentType = System.Net.Http.Headers.MediaTypeHeaderValue.Parse("application/json");
                request_.Content = content_;
                request_.Method = new System.Net.Http.HttpMethod("PUT");
                request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                var urlBuilder_ = new System.Text.StringBuilder();
                if (!string.IsNullOrEmpty(_baseUrl)) urlBuilder_.Append(_baseUrl);
                urlBuilder_.Append("api/CustomerAddress/update");
                urlBuilder_.Append('?');
                if (addressId != null) urlBuilder_.Append(System.Uri.EscapeDataString("AddressId")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(addressId, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                urlBuilder_.Length--;
                PrepareRequest(client_, request_, urlBuilder_);
                var url_ = urlBuilder_.ToString();
                request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);
                PrepareRequest(client_, request_, url_);

                var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                try
                {
                    var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                    foreach (var item_ in response_.Headers) headers_[item_.Key] = item_.Value;
                    if (response_.Content?.Headers != null)
                        foreach (var item_ in response_.Content.Headers) headers_[item_.Key] = item_.Value;
                    ProcessResponse(client_, response_);
                    var status_ = (int)response_.StatusCode;
                    if (status_ == 200)
                    {
                        var obj_ = await ReadObjectResponseAsync<Updated>(response_, headers_, cancellationToken).ConfigureAwait(false);
                        if (obj_.Object == null) throw new ApiException("Response was null which was not expected.", status_, obj_.Text, headers_, null);
                        return obj_.Object;
                    }
                    else if (status_ == 400) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Bad Request",            status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 401) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Unauthorized",          status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 404) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Not Found",             status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 409) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Conflict",              status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 500) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Internal Server Error", status_, obj_.Text, headers_, obj_.Object, null); }
                    else { var data_ = response_.Content == null ? null : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false); throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, data_, headers_, null); }
                }
                finally { response_.Dispose(); }
            }
        }

        /// <summary>DeleteAddress</summary>
        public virtual System.Threading.Tasks.Task<Deleted> DeleteAsync(System.Guid? addressId)
            => DeleteAsync(addressId, System.Threading.CancellationToken.None);

        public virtual async System.Threading.Tasks.Task<Deleted> DeleteAsync(System.Guid? addressId, System.Threading.CancellationToken cancellationToken)
        {
            var client_ = _httpClient;
            using (var request_ = new System.Net.Http.HttpRequestMessage())
            {
                request_.Method = new System.Net.Http.HttpMethod("DELETE");
                request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                var urlBuilder_ = new System.Text.StringBuilder();
                if (!string.IsNullOrEmpty(_baseUrl)) urlBuilder_.Append(_baseUrl);
                urlBuilder_.Append("api/CustomerAddress/delete");
                urlBuilder_.Append('?');
                if (addressId != null) urlBuilder_.Append(System.Uri.EscapeDataString("AddressId")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(addressId, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                urlBuilder_.Length--;
                PrepareRequest(client_, request_, urlBuilder_);
                var url_ = urlBuilder_.ToString();
                request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);
                PrepareRequest(client_, request_, url_);

                var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                try
                {
                    var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                    foreach (var item_ in response_.Headers) headers_[item_.Key] = item_.Value;
                    if (response_.Content?.Headers != null)
                        foreach (var item_ in response_.Content.Headers) headers_[item_.Key] = item_.Value;
                    ProcessResponse(client_, response_);
                    var status_ = (int)response_.StatusCode;
                    if (status_ == 200)
                    {
                        var obj_ = await ReadObjectResponseAsync<Deleted>(response_, headers_, cancellationToken).ConfigureAwait(false);
                        if (obj_.Object == null) throw new ApiException("Response was null which was not expected.", status_, obj_.Text, headers_, null);
                        return obj_.Object;
                    }
                    else if (status_ == 400) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Bad Request",            status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 401) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Unauthorized",          status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 404) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Not Found",             status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 409) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Conflict",              status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 500) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Internal Server Error", status_, obj_.Text, headers_, obj_.Object, null); }
                    else { var data_ = response_.Content == null ? null : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false); throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, data_, headers_, null); }
                }
                finally { response_.Dispose(); }
            }
        }

        // ── Customer ──────────────────────────────────────────────────────

        /// <summary>GetCustomers</summary>
        public virtual System.Threading.Tasks.Task<System.Collections.Generic.ICollection<CustomerDto>> Get2Async(System.Guid? customerId)
            => Get2Async(customerId, System.Threading.CancellationToken.None);

        public virtual async System.Threading.Tasks.Task<System.Collections.Generic.ICollection<CustomerDto>> Get2Async(System.Guid? customerId, System.Threading.CancellationToken cancellationToken)
        {
            var client_ = _httpClient;
            using (var request_ = new System.Net.Http.HttpRequestMessage())
            {
                request_.Method = new System.Net.Http.HttpMethod("GET");
                request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                var urlBuilder_ = new System.Text.StringBuilder();
                if (!string.IsNullOrEmpty(_baseUrl)) urlBuilder_.Append(_baseUrl);
                urlBuilder_.Append("api/Customer/get");
                urlBuilder_.Append('?');
                if (customerId != null) urlBuilder_.Append(System.Uri.EscapeDataString("CustomerId")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(customerId, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                urlBuilder_.Length--;
                PrepareRequest(client_, request_, urlBuilder_);
                var url_ = urlBuilder_.ToString();
                request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);
                PrepareRequest(client_, request_, url_);

                var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                try
                {
                    var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                    foreach (var item_ in response_.Headers) headers_[item_.Key] = item_.Value;
                    if (response_.Content?.Headers != null)
                        foreach (var item_ in response_.Content.Headers) headers_[item_.Key] = item_.Value;
                    ProcessResponse(client_, response_);
                    var status_ = (int)response_.StatusCode;
                    if (status_ == 200)
                    {
                        var obj_ = await ReadObjectResponseAsync<System.Collections.Generic.ICollection<CustomerDto>>(response_, headers_, cancellationToken).ConfigureAwait(false);
                        if (obj_.Object == null) throw new ApiException("Response was null which was not expected.", status_, obj_.Text, headers_, null);
                        return obj_.Object;
                    }
                    else if (status_ == 400) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Bad Request",            status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 401) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Unauthorized",          status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 404) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Not Found",             status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 409) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Conflict",              status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 500) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Internal Server Error", status_, obj_.Text, headers_, obj_.Object, null); }
                    else { var data_ = response_.Content == null ? null : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false); throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, data_, headers_, null); }
                }
                finally { response_.Dispose(); }
            }
        }

        /// <summary>GetCustomerHistory</summary>
        public virtual System.Threading.Tasks.Task<System.Collections.Generic.ICollection<CustomerHistoryDto>> History2Async(System.Guid? customerId)
            => History2Async(customerId, System.Threading.CancellationToken.None);

        public virtual async System.Threading.Tasks.Task<System.Collections.Generic.ICollection<CustomerHistoryDto>> History2Async(System.Guid? customerId, System.Threading.CancellationToken cancellationToken)
        {
            var client_ = _httpClient;
            using (var request_ = new System.Net.Http.HttpRequestMessage())
            {
                request_.Method = new System.Net.Http.HttpMethod("GET");
                request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                var urlBuilder_ = new System.Text.StringBuilder();
                if (!string.IsNullOrEmpty(_baseUrl)) urlBuilder_.Append(_baseUrl);
                urlBuilder_.Append("api/Customer/history");
                urlBuilder_.Append('?');
                if (customerId != null) urlBuilder_.Append(System.Uri.EscapeDataString("CustomerId")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(customerId, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                urlBuilder_.Length--;
                PrepareRequest(client_, request_, urlBuilder_);
                var url_ = urlBuilder_.ToString();
                request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);
                PrepareRequest(client_, request_, url_);

                var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                try
                {
                    var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                    foreach (var item_ in response_.Headers) headers_[item_.Key] = item_.Value;
                    if (response_.Content?.Headers != null)
                        foreach (var item_ in response_.Content.Headers) headers_[item_.Key] = item_.Value;
                    ProcessResponse(client_, response_);
                    var status_ = (int)response_.StatusCode;
                    if (status_ == 200)
                    {
                        var obj_ = await ReadObjectResponseAsync<System.Collections.Generic.ICollection<CustomerHistoryDto>>(response_, headers_, cancellationToken).ConfigureAwait(false);
                        if (obj_.Object == null) throw new ApiException("Response was null which was not expected.", status_, obj_.Text, headers_, null);
                        return obj_.Object;
                    }
                    else if (status_ == 400) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Bad Request",            status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 401) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Unauthorized",          status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 404) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Not Found",             status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 409) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Conflict",              status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 500) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Internal Server Error", status_, obj_.Text, headers_, obj_.Object, null); }
                    else { var data_ = response_.Content == null ? null : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false); throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, data_, headers_, null); }
                }
                finally { response_.Dispose(); }
            }
        }

        /// <summary>CreateCustomer</summary>
        public virtual System.Threading.Tasks.Task<CustomerDto> Add2Async(CreateCustomerReq body)
            => Add2Async(body, System.Threading.CancellationToken.None);

        public virtual async System.Threading.Tasks.Task<CustomerDto> Add2Async(CreateCustomerReq body, System.Threading.CancellationToken cancellationToken)
        {
            if (body == null) throw new System.ArgumentNullException("body");
            var client_ = _httpClient;
            using (var request_ = new System.Net.Http.HttpRequestMessage())
            {
                var json_ = Newtonsoft.Json.JsonConvert.SerializeObject(body, JsonSerializerSettings);
                var content_ = new System.Net.Http.StringContent(json_);
                content_.Headers.ContentType = System.Net.Http.Headers.MediaTypeHeaderValue.Parse("application/json");
                request_.Content = content_;
                request_.Method = new System.Net.Http.HttpMethod("POST");
                request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                var urlBuilder_ = new System.Text.StringBuilder();
                if (!string.IsNullOrEmpty(_baseUrl)) urlBuilder_.Append(_baseUrl);
                urlBuilder_.Append("api/Customer/add");
                PrepareRequest(client_, request_, urlBuilder_);
                var url_ = urlBuilder_.ToString();
                request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);
                PrepareRequest(client_, request_, url_);

                var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                try
                {
                    var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                    foreach (var item_ in response_.Headers) headers_[item_.Key] = item_.Value;
                    if (response_.Content?.Headers != null)
                        foreach (var item_ in response_.Content.Headers) headers_[item_.Key] = item_.Value;
                    ProcessResponse(client_, response_);
                    var status_ = (int)response_.StatusCode;
                    if (status_ == 200)
                    {
                        var obj_ = await ReadObjectResponseAsync<CustomerDto>(response_, headers_, cancellationToken).ConfigureAwait(false);
                        if (obj_.Object == null) throw new ApiException("Response was null which was not expected.", status_, obj_.Text, headers_, null);
                        return obj_.Object;
                    }
                    else if (status_ == 400) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Bad Request",            status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 401) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Unauthorized",          status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 404) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Not Found",             status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 409) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Conflict",              status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 500) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Internal Server Error", status_, obj_.Text, headers_, obj_.Object, null); }
                    else { var data_ = response_.Content == null ? null : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false); throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, data_, headers_, null); }
                }
                finally { response_.Dispose(); }
            }
        }

        /// <summary>UpdateCustomer</summary>
        public virtual System.Threading.Tasks.Task<Updated> Update2Async(System.Guid? customerId, UpdateCustomerReq body)
            => Update2Async(customerId, body, System.Threading.CancellationToken.None);

        public virtual async System.Threading.Tasks.Task<Updated> Update2Async(System.Guid? customerId, UpdateCustomerReq body, System.Threading.CancellationToken cancellationToken)
        {
            if (body == null) throw new System.ArgumentNullException("body");
            var client_ = _httpClient;
            using (var request_ = new System.Net.Http.HttpRequestMessage())
            {
                var json_ = Newtonsoft.Json.JsonConvert.SerializeObject(body, JsonSerializerSettings);
                var content_ = new System.Net.Http.StringContent(json_);
                content_.Headers.ContentType = System.Net.Http.Headers.MediaTypeHeaderValue.Parse("application/json");
                request_.Content = content_;
                request_.Method = new System.Net.Http.HttpMethod("PUT");
                request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                var urlBuilder_ = new System.Text.StringBuilder();
                if (!string.IsNullOrEmpty(_baseUrl)) urlBuilder_.Append(_baseUrl);
                urlBuilder_.Append("api/Customer/update");
                urlBuilder_.Append('?');
                if (customerId != null) urlBuilder_.Append(System.Uri.EscapeDataString("CustomerId")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(customerId, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                urlBuilder_.Length--;
                PrepareRequest(client_, request_, urlBuilder_);
                var url_ = urlBuilder_.ToString();
                request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);
                PrepareRequest(client_, request_, url_);

                var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                try
                {
                    var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                    foreach (var item_ in response_.Headers) headers_[item_.Key] = item_.Value;
                    if (response_.Content?.Headers != null)
                        foreach (var item_ in response_.Content.Headers) headers_[item_.Key] = item_.Value;
                    ProcessResponse(client_, response_);
                    var status_ = (int)response_.StatusCode;
                    if (status_ == 200)
                    {
                        var obj_ = await ReadObjectResponseAsync<Updated>(response_, headers_, cancellationToken).ConfigureAwait(false);
                        if (obj_.Object == null) throw new ApiException("Response was null which was not expected.", status_, obj_.Text, headers_, null);
                        return obj_.Object;
                    }
                    else if (status_ == 400) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Bad Request",            status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 401) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Unauthorized",          status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 404) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Not Found",             status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 409) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Conflict",              status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 500) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Internal Server Error", status_, obj_.Text, headers_, obj_.Object, null); }
                    else { var data_ = response_.Content == null ? null : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false); throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, data_, headers_, null); }
                }
                finally { response_.Dispose(); }
            }
        }

        /// <summary>DeleteCustomer</summary>
        public virtual System.Threading.Tasks.Task<Deleted> Delete2Async(System.Guid? customerId)
            => Delete2Async(customerId, System.Threading.CancellationToken.None);

        public virtual async System.Threading.Tasks.Task<Deleted> Delete2Async(System.Guid? customerId, System.Threading.CancellationToken cancellationToken)
        {
            var client_ = _httpClient;
            using (var request_ = new System.Net.Http.HttpRequestMessage())
            {
                request_.Method = new System.Net.Http.HttpMethod("DELETE");
                request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                var urlBuilder_ = new System.Text.StringBuilder();
                if (!string.IsNullOrEmpty(_baseUrl)) urlBuilder_.Append(_baseUrl);
                urlBuilder_.Append("api/Customer/delete");
                urlBuilder_.Append('?');
                if (customerId != null) urlBuilder_.Append(System.Uri.EscapeDataString("CustomerId")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(customerId, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                urlBuilder_.Length--;
                PrepareRequest(client_, request_, urlBuilder_);
                var url_ = urlBuilder_.ToString();
                request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);
                PrepareRequest(client_, request_, url_);

                var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                try
                {
                    var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                    foreach (var item_ in response_.Headers) headers_[item_.Key] = item_.Value;
                    if (response_.Content?.Headers != null)
                        foreach (var item_ in response_.Content.Headers) headers_[item_.Key] = item_.Value;
                    ProcessResponse(client_, response_);
                    var status_ = (int)response_.StatusCode;
                    if (status_ == 200)
                    {
                        var obj_ = await ReadObjectResponseAsync<Deleted>(response_, headers_, cancellationToken).ConfigureAwait(false);
                        if (obj_.Object == null) throw new ApiException("Response was null which was not expected.", status_, obj_.Text, headers_, null);
                        return obj_.Object;
                    }
                    else if (status_ == 400) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Bad Request",            status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 401) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Unauthorized",          status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 404) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Not Found",             status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 409) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Conflict",              status_, obj_.Text, headers_, obj_.Object, null); }
                    else if (status_ == 500) { var obj_ = await ReadObjectResponseAsync<ProblemDetails>(response_, headers_, cancellationToken).ConfigureAwait(false); throw new ApiException<ProblemDetails>("Internal Server Error", status_, obj_.Text, headers_, obj_.Object, null); }
                    else { var data_ = response_.Content == null ? null : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false); throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, data_, headers_, null); }
                }
                finally { response_.Dispose(); }
            }
        }

        // ── RabbitMQ ──────────────────────────────────────────────────────

        /// <summary>RabbitMQ Health Check</summary>
        public virtual System.Threading.Tasks.Task HealthAsync() => HealthAsync(System.Threading.CancellationToken.None);

        public virtual async System.Threading.Tasks.Task HealthAsync(System.Threading.CancellationToken cancellationToken)
        {
            var client_ = _httpClient;
            using (var request_ = new System.Net.Http.HttpRequestMessage())
            {
                request_.Method = new System.Net.Http.HttpMethod("GET");
                var urlBuilder_ = new System.Text.StringBuilder();
                if (!string.IsNullOrEmpty(_baseUrl)) urlBuilder_.Append(_baseUrl);
                urlBuilder_.Append("api/RabbitMQ_Management/health");
                PrepareRequest(client_, request_, urlBuilder_);
                request_.RequestUri = new System.Uri(urlBuilder_.ToString(), System.UriKind.RelativeOrAbsolute);
                PrepareRequest(client_, request_, urlBuilder_.ToString());
                var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                try
                {
                    ProcessResponse(client_, response_);
                    if ((int)response_.StatusCode == 200) return;
                    var data_ = response_.Content == null ? null : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false);
                    throw new ApiException("The HTTP status code of the response was not expected (" + (int)response_.StatusCode + ").", (int)response_.StatusCode, data_, new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>(), null);
                }
                finally { response_.Dispose(); }
            }
        }

        /// <summary>RabbitMQ Connections</summary>
        public virtual System.Threading.Tasks.Task ConnectionsAsync() => ConnectionsAsync(System.Threading.CancellationToken.None);

        public virtual async System.Threading.Tasks.Task ConnectionsAsync(System.Threading.CancellationToken cancellationToken)
        {
            var client_ = _httpClient;
            using (var request_ = new System.Net.Http.HttpRequestMessage())
            {
                request_.Method = new System.Net.Http.HttpMethod("GET");
                var urlBuilder_ = new System.Text.StringBuilder();
                if (!string.IsNullOrEmpty(_baseUrl)) urlBuilder_.Append(_baseUrl);
                urlBuilder_.Append("api/RabbitMQ_Management/connections");
                PrepareRequest(client_, request_, urlBuilder_);
                request_.RequestUri = new System.Uri(urlBuilder_.ToString(), System.UriKind.RelativeOrAbsolute);
                PrepareRequest(client_, request_, urlBuilder_.ToString());
                var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                try
                {
                    ProcessResponse(client_, response_);
                    if ((int)response_.StatusCode == 200) return;
                    var data_ = response_.Content == null ? null : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false);
                    throw new ApiException("The HTTP status code of the response was not expected (" + (int)response_.StatusCode + ").", (int)response_.StatusCode, data_, new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>(), null);
                }
                finally { response_.Dispose(); }
            }
        }

        /// <summary>RabbitMQ Queues</summary>
        public virtual System.Threading.Tasks.Task QueuesAsync() => QueuesAsync(System.Threading.CancellationToken.None);

        public virtual async System.Threading.Tasks.Task QueuesAsync(System.Threading.CancellationToken cancellationToken)
        {
            var client_ = _httpClient;
            using (var request_ = new System.Net.Http.HttpRequestMessage())
            {
                request_.Method = new System.Net.Http.HttpMethod("GET");
                var urlBuilder_ = new System.Text.StringBuilder();
                if (!string.IsNullOrEmpty(_baseUrl)) urlBuilder_.Append(_baseUrl);
                urlBuilder_.Append("api/RabbitMQ_Management/queues");
                PrepareRequest(client_, request_, urlBuilder_);
                request_.RequestUri = new System.Uri(urlBuilder_.ToString(), System.UriKind.RelativeOrAbsolute);
                PrepareRequest(client_, request_, urlBuilder_.ToString());
                var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                try
                {
                    ProcessResponse(client_, response_);
                    if ((int)response_.StatusCode == 200) return;
                    var data_ = response_.Content == null ? null : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false);
                    throw new ApiException("The HTTP status code of the response was not expected (" + (int)response_.StatusCode + ").", (int)response_.StatusCode, data_, new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>(), null);
                }
                finally { response_.Dispose(); }
            }
        }

        // ── Infrastructure ────────────────────────────────────────────────

        protected struct ObjectResponseResult<T>
        {
            public ObjectResponseResult(T responseObject, string responseText) { Object = responseObject; Text = responseText; }
            public T Object { get; }
            public string Text { get; }
        }

        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        private static System.Threading.Tasks.Task<string> ReadAsStringAsync(System.Net.Http.HttpContent content, System.Threading.CancellationToken cancellationToken)
        {
#if NET5_0_OR_GREATER
            return content.ReadAsStringAsync(cancellationToken);
#else
            return content.ReadAsStringAsync();
#endif
        }

        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        private static System.Threading.Tasks.Task<System.IO.Stream> ReadAsStreamAsync(System.Net.Http.HttpContent content, System.Threading.CancellationToken cancellationToken)
        {
#if NET5_0_OR_GREATER
            return content.ReadAsStreamAsync(cancellationToken);
#else
            return content.ReadAsStreamAsync();
#endif
        }

        public bool ReadResponseAsString { get; set; }

        protected virtual async System.Threading.Tasks.Task<ObjectResponseResult<T>> ReadObjectResponseAsync<T>(System.Net.Http.HttpResponseMessage response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, System.Threading.CancellationToken cancellationToken)
        {
            if (response == null || response.Content == null)
                return new ObjectResponseResult<T>(default(T), string.Empty);

            if (ReadResponseAsString)
            {
                var responseText = await ReadAsStringAsync(response.Content, cancellationToken).ConfigureAwait(false);
                try
                {
                    var typedBody = Newtonsoft.Json.JsonConvert.DeserializeObject<T>(responseText, JsonSerializerSettings);
                    return new ObjectResponseResult<T>(typedBody, responseText);
                }
                catch (Newtonsoft.Json.JsonException exception)
                {
                    throw new ApiException("Could not deserialize the response body string as " + typeof(T).FullName + ".", (int)response.StatusCode, responseText, headers, exception);
                }
            }
            else
            {
                try
                {
                    using var responseStream = await ReadAsStreamAsync(response.Content, cancellationToken).ConfigureAwait(false);
                    using var streamReader = new System.IO.StreamReader(responseStream);
                    using var jsonTextReader = new Newtonsoft.Json.JsonTextReader(streamReader);
                    var serializer = Newtonsoft.Json.JsonSerializer.Create(JsonSerializerSettings);
                    var typedBody = serializer.Deserialize<T>(jsonTextReader);
                    return new ObjectResponseResult<T>(typedBody, string.Empty);
                }
                catch (Newtonsoft.Json.JsonException exception)
                {
                    throw new ApiException("Could not deserialize the response body stream as " + typeof(T).FullName + ".", (int)response.StatusCode, string.Empty, headers, exception);
                }
            }
        }

        private string ConvertToString(object value, System.Globalization.CultureInfo cultureInfo)
        {
            if (value == null) return "";
            if (value is System.Enum)
            {
                var name = System.Enum.GetName(value.GetType(), value);
                if (name != null)
                {
                    var field_ = System.Reflection.IntrospectionExtensions.GetTypeInfo(value.GetType()).GetDeclaredField(name);
                    if (field_ != null)
                    {
                        var attribute = System.Reflection.CustomAttributeExtensions.GetCustomAttribute(field_, typeof(System.Runtime.Serialization.EnumMemberAttribute)) as System.Runtime.Serialization.EnumMemberAttribute;
                        if (attribute != null) return attribute.Value != null ? attribute.Value : name;
                    }
                    var converted = System.Convert.ToString(System.Convert.ChangeType(value, System.Enum.GetUnderlyingType(value.GetType()), cultureInfo));
                    return converted == null ? string.Empty : converted;
                }
            }
            else if (value is bool) return System.Convert.ToString((bool)value, cultureInfo).ToLowerInvariant();
            else if (value is byte[]) return System.Convert.ToBase64String((byte[])value);
            else if (value is string[]) return string.Join(",", (string[])value);
            else if (value.GetType().IsArray)
            {
                var arr = (System.Array)value;
                var parts = new string[arr.Length];
                for (var i = 0; i < arr.Length; i++) parts[i] = ConvertToString(arr.GetValue(i), cultureInfo);
                return string.Join(",", parts);
            }
            var result = System.Convert.ToString(value, cultureInfo);
            return result == null ? "" : result;
        }
    }

    // ── DTOs & Exceptions (unchanged from generated) ──────────────────────

    public partial class AddAddressReq
    {
        [Newtonsoft.Json.JsonProperty("type",  Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public int    Type  { get; set; }
        [Newtonsoft.Json.JsonProperty("value", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public string Value { get; set; }
        [Newtonsoft.Json.JsonExtensionData] public System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new System.Collections.Generic.Dictionary<string, object>();
    }

    public partial class AddressDto
    {
        [Newtonsoft.Json.JsonProperty("id",         Required = Newtonsoft.Json.Required.Always)] public System.Guid Id         { get; set; }
        [Newtonsoft.Json.JsonProperty("customerId", Required = Newtonsoft.Json.Required.Always)] public System.Guid CustomerId { get; set; }
        [Newtonsoft.Json.JsonProperty("type",       Required = Newtonsoft.Json.Required.Always)] public int         Type       { get; set; }
        [Newtonsoft.Json.JsonProperty("value",      Required = Newtonsoft.Json.Required.Always)] public string      Value      { get; set; }
        [Newtonsoft.Json.JsonExtensionData] public System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new System.Collections.Generic.Dictionary<string, object>();
    }

    public partial class AddressHistoryDto
    {
        [Newtonsoft.Json.JsonProperty("id",         Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public System.Guid        Id         { get; set; }
        [Newtonsoft.Json.JsonProperty("customerId", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public System.Guid        CustomerId { get; set; }
        [Newtonsoft.Json.JsonProperty("type",       Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public int                Type       { get; set; }
        [Newtonsoft.Json.JsonProperty("value",      Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public string             Value      { get; set; }
        [Newtonsoft.Json.JsonProperty("operation",  Required = Newtonsoft.Json.Required.Default,      NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public string             Operation  { get; set; }
        [Newtonsoft.Json.JsonProperty("validFrom",  Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public System.DateTimeOffset  ValidFrom  { get; set; }
        [Newtonsoft.Json.JsonProperty("validTo",    Required = Newtonsoft.Json.Required.Default,      NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public System.DateTimeOffset? ValidTo    { get; set; }
        [Newtonsoft.Json.JsonExtensionData] public System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new System.Collections.Generic.Dictionary<string, object>();
    }

    public partial class CreateAddressReq
    {
        [Newtonsoft.Json.JsonProperty("type",  Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public int    Type  { get; set; }
        [Newtonsoft.Json.JsonProperty("value", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public string Value { get; set; }
        [Newtonsoft.Json.JsonExtensionData] public System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new System.Collections.Generic.Dictionary<string, object>();
    }

    public partial class CreateCustomerReq
    {
        [Newtonsoft.Json.JsonProperty("name",     Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public string Name    { get; set; }
        [Newtonsoft.Json.JsonProperty("mobile",   Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public string Mobile  { get; set; }
        [Newtonsoft.Json.JsonProperty("adresses", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public System.Collections.Generic.ICollection<CreateAddressReq> Adresses { get; set; }
        [Newtonsoft.Json.JsonExtensionData] public System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new System.Collections.Generic.Dictionary<string, object>();
    }

    public partial class CustomerDto
    {
        [Newtonsoft.Json.JsonProperty("id",        Required = Newtonsoft.Json.Required.Always)] public System.Guid Id        { get; set; }
        [Newtonsoft.Json.JsonProperty("name",      Required = Newtonsoft.Json.Required.Always)] public string      Name      { get; set; }
        [Newtonsoft.Json.JsonProperty("mobile",    Required = Newtonsoft.Json.Required.Always)] public string      Mobile    { get; set; }
        [Newtonsoft.Json.JsonProperty("createdBy", Required = Newtonsoft.Json.Required.Always)] public string      CreatedBy { get; set; }
        [Newtonsoft.Json.JsonProperty("updatedBy", Required = Newtonsoft.Json.Required.Always)] public string      UpdatedBy { get; set; }
        [Newtonsoft.Json.JsonProperty("addresses", Required = Newtonsoft.Json.Required.Always)] public System.Collections.Generic.ICollection<AddressDto> Addresses { get; set; } = new System.Collections.ObjectModel.Collection<AddressDto>();
        [Newtonsoft.Json.JsonExtensionData] public System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new System.Collections.Generic.Dictionary<string, object>();
    }

    public partial class CustomerHistoryDto
    {
        [Newtonsoft.Json.JsonProperty("id",        Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public System.Guid        Id        { get; set; }
        [Newtonsoft.Json.JsonProperty("name",      Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public string             Name      { get; set; }
        [Newtonsoft.Json.JsonProperty("mobile",    Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public string             Mobile    { get; set; }
        [Newtonsoft.Json.JsonProperty("createdBy", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public string             CreatedBy { get; set; }
        [Newtonsoft.Json.JsonProperty("updatedBy", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public string             UpdatedBy { get; set; }
        [Newtonsoft.Json.JsonProperty("isDeleted", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public bool               IsDeleted { get; set; }
        [Newtonsoft.Json.JsonProperty("operation", Required = Newtonsoft.Json.Required.Default,      NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public string             Operation { get; set; }
        [Newtonsoft.Json.JsonProperty("validFrom", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public System.DateTimeOffset  ValidFrom { get; set; }
        [Newtonsoft.Json.JsonProperty("validTo",   Required = Newtonsoft.Json.Required.Default,      NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public System.DateTimeOffset? ValidTo   { get; set; }
        [Newtonsoft.Json.JsonExtensionData] public System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new System.Collections.Generic.Dictionary<string, object>();
    }

    public partial class Deleted
    {
        [Newtonsoft.Json.JsonExtensionData] public System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new System.Collections.Generic.Dictionary<string, object>();
    }

    public partial class Updated
    {
        [Newtonsoft.Json.JsonExtensionData] public System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new System.Collections.Generic.Dictionary<string, object>();
    }

    public partial class EntityTagHeaderValue
    {
        [Newtonsoft.Json.JsonProperty("tag",    Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public StringSegment Tag    { get; set; }
        [Newtonsoft.Json.JsonProperty("isWeak", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public bool          IsWeak { get; set; }
        [Newtonsoft.Json.JsonExtensionData] public System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new System.Collections.Generic.Dictionary<string, object>();
    }

    public partial class FileContentResult
    {
        [Newtonsoft.Json.JsonProperty("fileContents",        Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public byte[]                FileContents        { get; set; }
        [Newtonsoft.Json.JsonProperty("contentType",         Required = Newtonsoft.Json.Required.Default,      NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public string               ContentType         { get; set; }
        [Newtonsoft.Json.JsonProperty("fileDownloadName",    Required = Newtonsoft.Json.Required.Default,      NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public string               FileDownloadName    { get; set; }
        [Newtonsoft.Json.JsonProperty("lastModified",        Required = Newtonsoft.Json.Required.Default,      NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public System.DateTimeOffset? LastModified      { get; set; }
        [Newtonsoft.Json.JsonProperty("entityTag",           Required = Newtonsoft.Json.Required.Default,      NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public EntityTagHeaderValue  EntityTag           { get; set; }
        [Newtonsoft.Json.JsonProperty("enableRangeProcessing",Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public bool                 EnableRangeProcessing { get; set; }
        [Newtonsoft.Json.JsonExtensionData] public System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new System.Collections.Generic.Dictionary<string, object>();
    }

    public partial class GenerateTokenQuery
    {
        [Newtonsoft.Json.JsonProperty("email",    Required = Newtonsoft.Json.Required.Always)] public string Email    { get; set; }
        [Newtonsoft.Json.JsonProperty("password", Required = Newtonsoft.Json.Required.Always)] public string Password { get; set; }
        [Newtonsoft.Json.JsonExtensionData] public System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new System.Collections.Generic.Dictionary<string, object>();
    }

    public partial class ProblemDetails
    {
        [Newtonsoft.Json.JsonProperty("type",     Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public string Type     { get; set; }
        [Newtonsoft.Json.JsonProperty("title",    Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public string Title    { get; set; }
        [Newtonsoft.Json.JsonProperty("status",   Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public int?   Status   { get; set; }
        [Newtonsoft.Json.JsonProperty("detail",   Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public string Detail   { get; set; }
        [Newtonsoft.Json.JsonProperty("instance", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public string Instance { get; set; }
        [Newtonsoft.Json.JsonExtensionData] public System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new System.Collections.Generic.Dictionary<string, object>();
    }

    public partial class RefreshTokenQuery
    {
        [Newtonsoft.Json.JsonProperty("refreshToken",      Required = Newtonsoft.Json.Required.Always)] public string RefreshToken      { get; set; }
        [Newtonsoft.Json.JsonProperty("expiredAccessToken",Required = Newtonsoft.Json.Required.Always)] public string ExpiredAccessToken { get; set; }
        [Newtonsoft.Json.JsonExtensionData] public System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new System.Collections.Generic.Dictionary<string, object>();
    }

    public partial class StringSegment
    {
        [Newtonsoft.Json.JsonProperty("buffer",   Required = Newtonsoft.Json.Required.Default,      NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public string Buffer   { get; set; }
        [Newtonsoft.Json.JsonProperty("offset",   Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public int    Offset   { get; set; }
        [Newtonsoft.Json.JsonProperty("length",   Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public int    Length   { get; set; }
        [Newtonsoft.Json.JsonProperty("value",    Required = Newtonsoft.Json.Required.Default,      NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public string Value    { get; set; }
        [Newtonsoft.Json.JsonProperty("hasValue", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public bool   HasValue { get; set; }
        [Newtonsoft.Json.JsonExtensionData] public System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new System.Collections.Generic.Dictionary<string, object>();
    }

    public partial class TokenResponse
    {
        [Newtonsoft.Json.JsonProperty("accessToken",  Required = Newtonsoft.Json.Required.Default,      NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public string               AccessToken  { get; set; }
        [Newtonsoft.Json.JsonProperty("refreshToken", Required = Newtonsoft.Json.Required.Default,      NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public string               RefreshToken { get; set; }
        [Newtonsoft.Json.JsonProperty("expiresOnUtc", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public System.DateTimeOffset ExpiresOnUtc { get; set; }
        [Newtonsoft.Json.JsonExtensionData] public System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new System.Collections.Generic.Dictionary<string, object>();
    }

    public partial class UpdateAddressReq
    {
        [Newtonsoft.Json.JsonProperty("type",  Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public int    Type  { get; set; }
        [Newtonsoft.Json.JsonProperty("value", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public string Value { get; set; }
        [Newtonsoft.Json.JsonExtensionData] public System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new System.Collections.Generic.Dictionary<string, object>();
    }

    public partial class UpdateCustomerReq
    {
        [Newtonsoft.Json.JsonProperty("name",   Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public string Name   { get; set; }
        [Newtonsoft.Json.JsonProperty("mobile", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)] public string Mobile { get; set; }
        [Newtonsoft.Json.JsonExtensionData] public System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new System.Collections.Generic.Dictionary<string, object>();
    }

    public partial class ApiException : System.Exception
    {
        public int StatusCode { get; private set; }
        public string Response { get; private set; }
        public System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> Headers { get; private set; }

        public ApiException(string message, int statusCode, string response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, System.Exception innerException)
            : base(message + "\n\nStatus: " + statusCode + "\nResponse: \n" + ((response == null) ? "(null)" : response.Substring(0, response.Length >= 512 ? 512 : response.Length)), innerException)
        {
            StatusCode = statusCode;
            Response = response;
            Headers = headers;
        }

        public override string ToString() => string.Format("HTTP Response: \n\n{0}\n\n{1}", Response, base.ToString());
    }

    public partial class ApiException<TResult> : ApiException
    {
        public TResult Result { get; private set; }
        public ApiException(string message, int statusCode, string response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, TResult result, System.Exception innerException)
            : base(message, statusCode, response, headers, innerException) { Result = result; }
    }
}
