//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------


using Newtonsoft.Json;

namespace  Customer_Mangment_Integrate.Test.Common
{
    public partial class Client
    {

        public virtual async Task<TokenResponse> RequestPasswordTokenAsync(
            string userName,
            string password,
            string clientId = "customer-management-swagger", 
            string scope = "customer_api offline_access roles",
            CancellationToken cancellationToken = default)
        {
            var client_ = _httpClient;
            using var request_ = new HttpRequestMessage(HttpMethod.Post, "connect/token");

            var parameters = new Dictionary<string, string>
            {
                ["grant_type"] = "password",
                ["username"] = userName,
                ["password"] = password,
                ["client_id"] = clientId,
                ["scope"] = scope
            };

            request_.Content = new FormUrlEncodedContent(parameters);
            request_.Headers.Accept.ParseAdd("application/json");

            var response_ = await client_.SendAsync(request_, cancellationToken).ConfigureAwait(false);
            var headers_ = new Dictionary<string, IEnumerable<string>>();
            foreach (var h in response_.Headers) headers_[h.Key] = h.Value;
            if (response_.Content?.Headers != null)
                foreach (var h in response_.Content.Headers) headers_[h.Key] = h.Value;

            var status_ = (int)response_.StatusCode;
            var responseText = await response_.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);

            if (status_ == 200)
            {
                var tokenResponse = JsonConvert.DeserializeObject<TokenResponse>(responseText, JsonSerializerSettings);
                if (tokenResponse == null)
                    throw new ApiException("Response was null", status_, responseText, headers_, null);
                return tokenResponse;
            }

            throw new ApiException($"Token request failed with status {status_}", status_, responseText, headers_, null);
        }

        /// <summary>
        /// Refreshes an access token using a refresh token.
        /// </summary>
        public virtual async Task<TokenResponse> RequestRefreshTokenAsync(
            string refreshToken,
            string clientId = "customer-management-swagger",

            CancellationToken cancellationToken = default)
        {
            var client_ = _httpClient;
            using var request_ = new HttpRequestMessage(HttpMethod.Post, "connect/token");

            var parameters = new Dictionary<string, string>
            {
                ["grant_type"] = "refresh_token",
                ["refresh_token"] = refreshToken,
                ["client_id"] = clientId,
            };

            request_.Content = new FormUrlEncodedContent(parameters);
            request_.Headers.Accept.ParseAdd("application/json");

            var response_ = await client_.SendAsync(request_, cancellationToken).ConfigureAwait(false);
            var headers_ = new Dictionary<string, IEnumerable<string>>();
            foreach (var h in response_.Headers) headers_[h.Key] = h.Value;
            if (response_.Content?.Headers != null)
                foreach (var h in response_.Content.Headers) headers_[h.Key] = h.Value;

            var status_ = (int)response_.StatusCode;
            var responseText = await response_.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);

            if (status_ == 200)
            {
                var tokenResponse = JsonConvert.DeserializeObject<TokenResponse>(responseText, JsonSerializerSettings);
                if (tokenResponse == null)
                    throw new ApiException("Response was null", status_, responseText, headers_, null);
                return tokenResponse;
            }

            throw new ApiException($"Token refresh failed with status {status_}", status_, responseText, headers_, null);
        }
    }



}
